/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.odu.cs.cs350;

import org.junit.Test;
import java.io.BufferedReader;
import static org.junit.Assert.*;

/**
 * @author skotei
 * @author ashahid
 */

public class RunProjectionTest {
    @Test 
    public void testAppHasAGreeting() {
       // RunProjection classUnderTest = new RunProjection();
        //assertNotNull("app should have a program heading", classUnderTest.readSemesters(BufferedReader));
        //assertNotNull("app should have a compute projection", classUnderTest.computeProjection(List<Semester>));
    }
    
//    @Test
//    public void testCalculateProjection {
//    	RunProjection testRP = new RunProjection();
//    }
}
